# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempest < Formula
  desc ""
  homepage "https://tempestdx.com/"
  version "0.1.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tempestdx/cli/releases/download/v0.1.13/tempest_Darwin_x86_64.tar.gz"
      sha256 "8c6ef89254be82ab7fdfe3cd0bccc51e38d49869721cd6735a49fc35366f4b97"

      def install
        bin.install "tempest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tempestdx/cli/releases/download/v0.1.13/tempest_Darwin_arm64.tar.gz"
      sha256 "d7071978de1727b29429df749d6cc05af8b08e07a2753ce2b887e3183bcb7080"

      def install
        bin.install "tempest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tempestdx/cli/releases/download/v0.1.13/tempest_Linux_x86_64.tar.gz"
        sha256 "a5ab240f208aad1e458760c5e3b5e65f62b1b757bd186f1f5f4021ed3740a1fd"

        def install
          bin.install "tempest"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tempestdx/cli/releases/download/v0.1.13/tempest_Linux_arm64.tar.gz"
        sha256 "ae098a9ecdcb44d00504605fd506d957f9a5f9cdb9169d0d15de5dbcb7ce0635"

        def install
          bin.install "tempest"
        end
      end
    end
  end
end
